version: '3'
services:
  my_influxdb:
    container_name: 'my_influxdb'
    build: ./influxdb
    ports:
      - '8086:8086'
      - '8088:8088'
    volumes:
      - influxdb-volume:/var/lib/influxdb
  my_grafana:
    container_name: 'my_grafana'
    build: ./grafana
    ports:
      - '3000:3000'
    depends_on:
      - my_influxdb
volumes:
  influxdb-volume:
